id: P9456EDB4
initial_creation_type: ocr
source_metadata:
  volumes:
    8eaef2c37b5747e9ad428455b8616a24:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: འབྲེལ་པ་བརྟག་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
