id: DFBF4DEB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:44:04+00:00'
last_modified: '2022-05-30T04:44:40.453407+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    27c6:
      image_group_id: I1PD95942
      title: འབྲེལ་པ་བརྟག་པའི་འགྲེལ་པ།
      total_pages: 1198
      order: 97
      base_file: 27c6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
